### ISSUE TITLE
Install Google Analytics tracking code

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/opentargets.github.io#95]
- [x] Create new Google Analytics tracking code for Open Targets Corporate Website
- [x] Install tracking code in ``_includes`` directory with own HTML file
- [x] Remove Piwik tracking code

**Comment by andrewhercules** [comment]
Ticket closed as Google Analytics code installed
